### ISSUE TITLE
【bug】小米mix2s 手机端app闪退无法使用

### ISSUE THREAD

**Issue by blackpancake** [weixiansen574/HybridFileXfer#16]
机型：小米 Mix2s
电脑插的是usb3.0接口，已打开usb调试，未打开usb安全调试

![Screenshot_2024-05-02-21-00-29-059_top weixiansen574 hybridfilexfer](https://github.com/weixiansen574/HybridFileXfer/assets/62934143/af67dcc6-c788-40b5-842e-74afebc2cf29)
在成功连接后点击“传输文件”后进入下一个界面瞬间闪退
![IMG_20240502_210347](https://github.com/weixiansen574/HybridFileXfer/assets/62934143/758869cd-cf39-47e3-81ce-5240847378f9)
（此为闪退瞬间抓拍）
电脑服务端报错：
```D:\双轨快传_v1.1.1>java -jar HybridFileXfer.jar
USB : 5740 端口转发成功！
USB : 5741 端口转发成功！
正在连接手机……
已连接至手机！WLAN IP:192.168.0.101
获取文件列表 /
usbReceive 接收线程已终止，因为发生了异常
java.io.EOFException
        at java.base/java.io.DataInputStream.readShort(DataInputStream.java:321)
        at top.weixiansen574.hybridfilexfer.core.threads.ClientControllerThread.waitingForRequest(ClientControllerThread.java:106)
        at top.weixiansen574.hybridfilexfer.core.threads.ClientControllerThread.run(ClientControllerThread.java:86)
java.io.EOFException

D:\双轨快传_v1.1.1>pause
请按任意键继续. . .
```

多次测试100%复现

**Comment by flt6** [comment]
Huawei Nova 复现100%
注意到没有“允许访问全部文件”的申请，同时pm grant无法授予android.permission.MANAGE_EXTERNAL_STORAGE：
```
adb shell pm grant top.weixiansen574.hybridfilexfer android.permission.MANAGE_EXTERNAL_STORAGE

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown permission: android.permission.MANAGE_EXTERNAL_STORAGE

```

**Comment by weixiansen574** [comment]
OMG，系统不是安卓11以上的吧，所有文件权限是安卓11新增的权限，低于11的系统是存储权限，这个我忘记做适配了。五一放假电脑不在身边，你忍一下吧:(，回来我再给他修复了。不过我没有低于安卓11的设备，你要与我一起测试

**Comment by flt6** [comment]
系统是鸿蒙2.0.0的，这里补充logcat：
```log
:05-02 21:19:36.429  2015  2051 I ActivityTaskManager: Displayed top.weixiansen574.hybridfilexfer/.MainActivity: +217ms
5835:05-02 21:19:36.431  2015  2038 I WindowManager: removeIfPossible: Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer} callers=com.android.server.wm.WindowState.removeIfPossible:5154524 com.android.server.wm.WindowManagerService.removeWindow:4757696 android.view.ViewRootImpl.dispatchDetachedFromWindow:3533692 android.view.ViewRootImpl.doDie:3531716 android.view.ViewRootImpl$ViewRootHandler.handleMessage:5059208 
5837:05-02 21:19:36.431  2015  2038 I WindowManager: Not removing Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer EXITING} due to exit animation 
5842:05-02 21:19:36.440  2015  3115 V ActivityTaskManager: Activity idle: Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}
5857:05-02 21:19:36.532  2015  2038 I WindowManager: Exit animation finished in Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer EXITING}: remove=true
5858:05-02 21:19:36.532  2015  2038 E WindowManager: win=Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
5859:05-02 21:19:36.533  2015  2038 I WindowManager: postWindowRemoveCleanupLocked: Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer}
5860:05-02 21:19:36.533  2015  2038 I WindowManager: Removing Window{acb7851 u0 Splash Screen top.weixiansen574.hybridfilexfer} from AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}
5951:05-02 21:19:36.848  1010  1010 I AGPService: aps-info: focus pkgName - top.weixiansen574.hybridfilexfer, with 0 more apps
5953:05-02 21:19:36.848  1010  1010 I AGPService: FrameRateManager: aps-info: new pkgName - top.weixiansen574.hybridfilexfer, type - -1
5954:05-02 21:19:36.848  1010  1010 I AGPService: GpuPolicyManager: m_currentPkgName - top.weixiansen574.hybridfilexfer
5962:05-02 21:19:37.363  6875  8291 I ContentSensor_PackageUtil: pkgName : top.weixiansen574.hybridfilexfer
6014:05-02 21:19:38.367  2730  3393 D ConnCureConfigUtil: isCaredApp: input = top.weixiansen574.hybridfilexfer
6084:05-02 21:19:39.095  2015  6768 I HwApsManagerConfig: registerCallbackLocked success, pkgName:top.weixiansen574.hybridfilexfer, callback_count:75
6085:05-02 21:19:39.095  2015  6768 I HwApsManagerConfig: doCallbackAtFirstRegisterLocked, start ! pkgName:top.weixiansen574.hybridfilexfer
6087:05-02 21:19:39.095 23357 23357 D Hwaps   : APS: EventAnalyzed: registerCallbackInApsManagerService, mPkgName:top.weixiansen574.hybridfilexfer; result = true
6091:05-02 21:19:39.098  2015  6768 V ActivityManager: startProcess: name=top.weixiansen574.hybridfilexfer:TransferService app=null knownToBeDead=true thread=null pid=-1 preloadStatus=-1
6093:05-02 21:19:39.107  2015  2055 I ActivityManager: Start proc 23429:top.weixiansen574.hybridfilexfer:TransferService/u0a492 for service {top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferServices}
6106:05-02 21:19:39.127 23429 23429 D ApplicationLoaders: createClassLoader zip: /data/app/top.weixiansen574.hybridfilexfer-xaT-sjumFUjVcH-LBcugKA==/base.apk librarySearchPath: /data/app/top.weixiansen574.hybridfilexfer-xaT-sjumFUjVcH-LBcugKA==/lib/arm64 libraryPermittedPath: /data/user/0/top.weixiansen574.hybridfilexfer parent: java.lang.BootClassLoader@8070c37 targetSdkVersion: 34 isBundled: false classLoaderName: null sharedLibraries: null
6107:05-02 21:19:39.135 23429 23447 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=top.weixiansen574.hybridfilexfer#10492#256
6109:05-02 21:19:39.135 23429 23447 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=top.weixiansen574.hybridfilexfer#10492#0
6115:05-02 21:19:39.137 23429 23447 I AwareBitmapCacher: init processName:top.weixiansen574.hybridfilexfer:TransferService pid=23429 uid=10492
6117:05-02 21:19:39.137 23429 23429 D TransferServices: onBind被调用了，binder:top.weixiansen574.hybridfilexfer.TransferServiceBinder@278f2d3
6118:05-02 21:19:39.138 23357 23357 I System.out: 已连接service，IBinder:android.os.BinderProxy@e80ce5a iTransferService:top.weixiansen574.hybridfilexfer.ITransferService$Stub$Proxy@f53788b
6261:05-02 21:19:40.951  2778  5628 I ThermalTraceService: code:1, appInfo:top.weixiansen574.hybridfilexfer#10000, levelInfo:28,warm_shell_game,1#28,warm_shell_hc,1#28,warm_shell_default,1#0,warm_chg_cpu,1#0,warm_bschg_cpu,1#28,warm_shell,1#28,warm_shell_cap,1
6299:05-02 21:19:41.998 23357 23464 D ProfileInstaller: Skipping profile installation for top.weixiansen574.hybridfilexfer
6503:05-02 21:19:45.469  2015  2149 I ActivityTaskManager: START u0 {hwFlg=0x10 cmp=top.weixiansen574.hybridfilexfer/.TransferActivity (has extras)} from uid 10492
6507:05-02 21:19:45.470  2015  2149 I ActivityTaskManager: ActivityRecord info: ActivityInfo{b09db62 top.weixiansen574.hybridfilexfer.TransferActivity}
6508:05-02 21:19:45.470  2015  2149 D ActivityTaskManager: TaskLaunchParamsModifier:task=null activity=ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t-1} display-from-source=0 display-id=0 display-windowing-mode=1
6509:05-02 21:19:45.470  2015  2149 D ActivityTaskManager: TaskLaunchParamsModifier:task=null activity=ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t-1} display-from-source=0 display-id=0 display-windowing-mode=1 activity-options-fullscreen=Rect(0, 0 - 0, 0) non-freeform-display maximized-bounds
6511:05-02 21:19:45.472  2015  2149 I WindowManager: addWindowToken: displayid:0 binder:Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}} token:AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}
6513:05-02 21:19:45.472  2015  2149 V ActivityTaskManager: addAppToken: AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}} task={taskId=465 appTokens=[AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}] mdr=false} at 2147483647
6514:05-02 21:19:45.474  2015  2149 I ActivityTaskManager: setAppStartingWindow: token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}} pkg=top.weixiansen574.hybridfilexfer transferFrom=null newTask=false taskSwitch=false processRunning=true allowTaskSnapshot=true activityCreated=false LowRamTaskSnapshots=false
6524:05-02 21:19:45.487  2015  2149 I ActivityTaskManager: Making visible and scheduling visibility: ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}
6531:05-02 21:19:45.490  2015  2149 I WindowManager: Changing focus from Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:6654948 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6654424 com.android.server.wm.ActivityDisplay.setFocusedApp:5469864 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5468880 
6536:05-02 21:19:45.494  2015  2149 I WindowManager: Check opening app=AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}: allDrawn=false startingDisplayed=false startingMoved=false isRelaunching()=false startingWindow=null
6538:05-02 21:19:45.495  2015  2047 I HwAudioServiceEx: ComponentInfo : className = top.weixiansen574.hybridfilexfer.MainActivity, flag = onPause, isHomeActivity = , isTop = false
6539:05-02 21:19:45.495  2730  3393 D DollieActivityManagerAdapter: [Paused] pid:23357 uid:10492 ComponentInfo{top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity} uidState:2
6543:05-02 21:19:45.496  2015  2037 V ActivityTaskManager: Stopping Acti
vityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}: nowVisible=false animating=true finishing=false
6545:05-02 21:19:45.505 23357 23357 I DecorView[]: pkgName:top.weixiansen574.hybridfilexfer old windowMode:0 new windoMode:1, isFixedSize:false
6547:05-02 21:19:45.527 23357 23357 D ActivityThread: add activity client record, r= ActivityRecord{35567c5 token=android.os.BinderProxy@af1e75f {top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}} token= android.os.BinderProxy@af1e75f
6550:05-02 21:19:45.530  2015  2149 I HwPCUtils#HwRioViewManager: check if rio enable, displayId = 0， packageName = top.weixiansen574.hybridfilexfer
6552:05-02 21:19:45.532  2015  2149 I WindowManager: addWindow: Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} client:android.os.BinderProxy@ae19129 currentDisplayId:0 requestDisplayId:0 token:Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}
6554:05-02 21:19:45.535  2730  3393 D DollieActivityManagerAdapter: [Resumed] bg:false pid:23357 uid:10492 ComponentInfo{top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}
6555:05-02 21:19:45.535  2730  3393 E DollieAdapterService: notifyActivityState pkg:top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity state:2 fg:true mUid:10492
6556:05-02 21:19:45.535  2730  6313 I Hicom_Monitor: mActivityNotifierEx, className = top.weixiansen574.hybridfilexfer.TransferActivity, uid = 10492
6557:05-02 21:19:45.535  6991 21789 I CAWARENESS_20423_AppUsageManager: onEvent, packageName=top.weixiansen574.hybridfilexfer, activityName=top.weixiansen574.hybridfilexfer.TransferActivity, uid=10492
6575:05-02 21:19:45.538 23357 23493 D HiTouch_PressGestureDetector: onAttached, package=top.weixiansen574.hybridfilexfer, windowType=1, mIsHiTouchRestricted=false
6577:05-02 21:19:45.538  2015  2047 I HwAudioServiceEx: ComponentInfo : className = top.weixiansen574.hybridfilexfer.TransferActivity, flag = onResume, isHomeActivity = , isTop = true
6582:05-02 21:19:45.539  2015  3840 I WindowManager: Check opening app=AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}: allDrawn=false startingDisplayed=false startingMoved=false isRelaunching()=false startingWindow=null
6591:05-02 21:19:45.542  2015  3840 I WindowManager: Changing focus from null to Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:6654948 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6654424 com.android.server.wm.WindowManagerService.relayoutWindow:6257788 com.android.server.wm.Session.relayout:6262484 
6594:05-02 21:19:45.542  6991 23495 I CAWARENESS_20423_AppUsageFilterAbility: publishData top.weixiansen574.hybridfilexfer top.weixiansen574.hybridfilexfer.TransferActivity
6599:05-02 21:19:45.542  6991 23495 I CAWARENESS_20423_AppUsageFilterAbility: publishData top.weixiansen574.hybridfilexfer top.weixiansen574.hybridfilexfer.TransferActivity
6600:05-02 21:19:45.542  2015  2035 D StatusBarManagerService: win:Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}mIsColorEnable:truelight:false
6602:05-02 21:19:45.542  2015  2035 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}
6605:05-02 21:19:45.542  6991 23495 I CAWARENESS_20423_AppUsageFilterAbility: publishData top.weixiansen574.hybridfilexfer top.weixiansen574.hybridfilexfer.TransferActivity
6610:05-02 21:19:45.542  6991 23495 I CAWARENESS_20423_AppUsageFilterAbility: publishData top.weixiansen574.hybridfilexfer top.weixiansen574.hybridfilexfer.TransferActivity
6622:05-02 21:19:45.559 23357 23357 I System.out: TransferActivity 已连接service，IBinder:android.os.BinderProxy@e80ce5a iTransferService:top.weixiansen574.hybridfilexfer.ITransferService$Stub$Proxy@eb160ce
6625:05-02 21:19:45.560  2015  2038 I WindowManager: Check opening app=AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}: allDrawn=true startingDisplayed=false startingMoved=false isRelaunching()=false startingWindow=null
6630:05-02 21:19:45.561  2015  2038 D HwWindowManagerServiceEx: is app exit to launcher info: transit = 6, app = AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}, window = Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity}, mClosingApps = {AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}}, topOpeningApp = AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}, mExitIconBitmap = android.graphics.Bitmap@acc8b89, mExitIconHeight = 174, mExitIconWidth = 174
6633:05-02 21:19:45.563  2015  2038 V WindowManager: commitVisibility: AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}: hidden=true hiddenRequested=true
6634:05-02 21:19:45.564  2015  2038 D HwWindowManagerServiceEx: is app exit to launcher info: transit = 6, app = AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}, window = Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}, mClosingApps = {AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}}, topOpeningApp = AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}, mExitIconBitmap = android.graphics.Bitmap@acc8b89, mExitIconHeight = 174, mExitIconWidth = 174
6637:05-02 21:19:45.566  2015  2038 V WindowManager: commitVisibility: AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}: hidden=false hiddenRequested=false
6638:05-02 21:19:45.566 23429 23487 D TransferService: top.weixiansen574.hybridfilexfer.TransferServiceBinder@278f2d3
6639:05-02 21:19:45.567  2015  2038 I WindowManager: dispatchResized : win = Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} drawState = HAS_DRAWN
6672:05-02 21:19:45.594 23357 23357 I QarthLog: [PatchStore] create disable file for top.weixiansen574.hybridfilexfer uid is 10492
6674:05-02 21:19:45.594 23357 23357 E AndroidRuntime: Process: top.weixiansen574.hybridfilexfer, PID: 23357
6676:05-02 21:19:45.594 23357 23357 E AndroidRuntime: 	at top.weixiansen574.hybridfilexfer.IIServiceFileSelectAdapter.getItemCount(Unknown Source:2)
6729:05-02 21:19:45.596  2015  3840 W ActivityTaskManager:   finishTopCrashedActivityLocked Force finishing activity top.weixiansen574.hybridfilexfer/.TransferActivity
6731:05-02 21:19:45.598  2015  3840 W ActivityTaskManager:   finishTopCrashedActivityLocked non_home Force finishing activity top.weixiansen574.hybridfilexfer/.MainActivity
6734:05-02 21:19:45.599  2015  3840 I WindowManager: Changing focus from Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:6654948 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6654424 com.android.server.wm.DisplayContent.layoutAndAssignWindowLayersIfNeeded:6004212 com.android.server.wm.DisplayContent.positionStackAt:5732208 
6740:05-02 21:19:45.600  2015  3840 W HwActivityTaskManagerServiceEx: setResumedActivityUncheckLocked start call, from: ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivit
y t465 f}, to: ActivityRecord{b0085c2 u0 com.huawei.android.launcher/.unihome.UniHomeLauncher t419}
6741:05-02 21:19:45.600  2015  3840 W HwActivityTaskManagerServiceEx: appSwitch from: top.weixiansen574.hybridfilexfer to: com.huawei.android.launcher
6750:05-02 21:19:45.602  2778  3261 I ScenarioService: app focus change from: top.weixiansen574.hybridfilexfer to:com.huawei.android.launcher
6760:05-02 21:19:45.605  2730  4618 I AssistantService-11.2.1.200: registerHwActivityNotifier call fromPackage:top.weixiansen574.hybridfilexfer, toPackage:com.huawei.android.launcher
6762:05-02 21:19:45.605  2730  8003 D AssistantService-11.2.1.200: handleMessage app switch fromPackage:top.weixiansen574.hybridfilexfer, toPackage:com.huawei.android.launcher
6773:05-02 21:19:45.608  2730  3579 I Hicom_PolicyCenter: handleForegroundAppChanged. curPkgName: com.huawei.android.launcher, lastPkgName: top.weixiansen574.hybridfilexfer, curPkgUid: 10079, lastPkgUid: 10492
6833:05-02 21:19:45.625  2015  2205 W InputDispatcher: channel 'b434251 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
6834:05-02 21:19:45.625  2015  2205 E InputDispatcher: channel 'b434251 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
6835:05-02 21:19:45.625  2015  2205 W InputDispatcher: channel 'b065a99 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
6837:05-02 21:19:45.626  2015  2205 E InputDispatcher: channel 'b065a99 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
6838:05-02 21:19:45.626  2015  2205 I WindowManager: WINDOW DIED Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}
6842:05-02 21:19:45.626  2015  2205 I WindowManager: Animation done in AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}} isHidden:false hiddenRequested:true
6845:05-02 21:19:45.626  2015  2205 V ActivityTaskManager: Stopping ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465 f}: nowVisible=false animating=true finishing=true
6849:05-02 21:19:45.627  2015  2205 I WindowManager: removeIfPossible: Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} callers=com.android.server.wm.WindowState.removeIfPossible:5154524 com.android.server.wm.InputManagerCallback.notifyInputChannelBroken:3949360 com.android.server.input.InputManagerService.notifyInputChannelBroken:3965804 <bottom of call stack> <bottom of call stack> 
6850:05-02 21:19:45.627  2015  2205 W InputDispatcher: Attempted to unregister already unregistered input channel 'b434251 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity (server)'
6851:05-02 21:19:45.627  2015  2205 I WindowManager: Not removing Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING} due to exit animation 
6858:05-02 21:19:45.633  2015  3842 I WindowManager: WIN DEATH: Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity}
6861:05-02 21:19:45.633  2015  3842 I WindowManager: Animation done in AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}} isHidden:true hiddenRequested:true
6862:05-02 21:19:45.633  2015  3842 I WindowManager: removeIfPossible: Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity} callers=com.android.server.wm.WindowState$DeathRecipient.binderDied:3954452 android.os.BinderProxy.sendDeathNotice:5341628 <bottom of call stack> <bottom of call stack> <bottom of call stack> 
6863:05-02 21:19:45.633  2015  3842 W InputDispatcher: Attempted to unregister already unregistered input channel 'b065a99 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity (server)'
6864:05-02 21:19:45.634  2015  3842 I WindowManager: postWindowRemoveCleanupLocked: Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity}
6865:05-02 21:19:45.634  2015  3842 I WindowManager: Removing Window{b065a99 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.MainActivity} from AppWindowToken{b735759 token=Token{ba26d5d ActivityRecord{b433f44 u0 top.weixiansen574.hybridfilexfer/.MainActivity t465}}}
6867:05-02 21:19:45.637  2015  2993 I WindowManager: WIN DEATH: Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING}
6870:05-02 21:19:45.637  2015  2993 I WindowManager: removeIfPossible: Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING} callers=com.android.server.wm.WindowState$DeathRecipient.binderDied:3954452 android.os.BinderProxy.sendDeathNotice:5341628 <bottom of call stack> <bottom of call stack> <bottom of call stack> 
6871:05-02 21:19:45.637  2015  2993 I WindowManager: Not removing Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING} due to exit animation 
6875:05-02 21:19:45.642  2015  6768 I ActivityManager: Process top.weixiansen574.hybridfilexfer (pid 23357) has died: vis+99 TOP 
6878:05-02 21:19:45.642  2015  6768 D ActivityManager: cleanUpApplicationRecord app: 23357:top.weixiansen574.hybridfilexfer/u0a492, bad: false, restarting: false, allowRestart: true
6881:05-02 21:19:45.643  2015  6768 I WindowManager: removeWindowToken: displayid:0 binder:Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465 f}} token:AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}
6882:05-02 21:19:45.643  2015  6768 V WindowManager: commitVisibility: AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}: hidden=true hiddenRequested=true
6883:05-02 21:19:45.643  2015  6768 I WindowManager: Animation done in AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}} isHidden:true hiddenRequested:true
6884:05-02 21:19:45.644  2015  6768 I WindowManager: Exit animation finished in Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING}: remove=true
6885:05-02 21:19:45.644  2015  6768 E WindowManager: win=Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
6886:05-02 21:19:45.644  2015  6768 I WindowManager: postWindowRemoveCleanupLocked: Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity}
6887:05-02 21:19:45.644  2015  6768 I WindowManager: Removing Window{b434251 u0 top.weixiansen574.hybridfilexfer/top.weixiansen574.hybridfilexfer.TransferActivity} from AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}}
6894:05-02 21:19:45.647  2015  6768 V WindowManager: removeAppToken: AppWindowToken{b580559 token=Token{b52b1f8 ActivityRecord{b663e48 u0 top.weixiansen574.hybridfilexfer/.TransferActivity t465}}} delayed=true Callers=com.android.server.wm.DisplayContent.removeAppToken:5514376 com.android.server.wm.ActivityRecord.removeWindowContainer:5515444 com.android.server.wm.ActivityStack.removeActivityFromHistoryLocked:5516172 com.android.server.wm.ActivityStack.removeHistoryRecordsForAppLocked:6206644 com.android.server.wm.ActivityStack.handleAppDiedLocked:6207292 com.android.server.wm.RootActivityContainer.handleAppD
```

**Comment by flt6** [comment]
我这里甚至没有Android studio环境...
那只是adb+vscode插件而已

**Comment by flt6** [comment]
补充，经测试您的代码很规范，在Android 13（鸿蒙3.0.0.196）测试通过，允许访问全部文件自动唤醒。

所以，bug找错了...
