### ISSUE TITLE
接收线程已终止，因为发生了异常

### ISSUE THREAD

**Issue by jacobin** [weixiansen574/HybridFileXfer#34]
wifiReceive 接收线程已终止，因为发生了异常
java.io.FileNotFoundException: **C:\1111\DCIM\.qqpim_guid\V9sXJwkOUgqtxYbWtVxsSTCR6dNvQX2smPH\sKF49x1uB30Uct\P1Q==**
_qqpim_guid.dat (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
        at top.weixiansen574.hybridfilexfer.core.threads.ReceiveThread.run(ReceiveThread.java:43)

**Comment by jacobin** [comment]
现在改用FileZilla/PC+CxFileManager/Andrew解决问题。记得在FileZilla里勾上1）“Preserve timestamps of transferred files”2）“Force showing hidden filles ”

**Comment by freemedom** [comment]
@jacobin ftp传小文件速度太慢了

**Comment by freemedom** [comment]
不过说实话，我没看出来这个文件名有什么特殊字符

**Comment by jacobin** [comment]
> 不过说实话，我没看出来这个文件名有什么特殊字符

文件名有什么特殊字符，不是这里问题的本质。安卓端直接断头闪退，这是最低级的错误。

**Comment by freemedom** [comment]
我倒是没碰到安装端闪退的问题

**Comment by jacobin** [comment]
> 我倒是没碰到安装端闪退的问题

你在DCIM里一张张的复选而后一票传输当然不会碰上此类问题。这相当于你的细心为它规避了异常风险，是保护性的使用。
我不想花这个时间侍候它，简单直接，把DCIM一拽就往PC上扔过去。这种操作，大概率会发生大妈大爷哄抢开业商场的免费鸡蛋的火爆情景。

**Comment by TJNOV** [comment]
USB_ADB_receive 已中断，如果本程序（电脑端）没有正常结束，请手动关闭！
java.util.concurrent.ExecutionException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at top.weixiansen574.hybirdfilexfer.core.HFXClient.handleReceiveFiles(HFXClient.java:240)
        at top.weixiansen574.hybirdfilexfer.core.HFXClient.start(HFXClient.java:111)
        at top.weixiansen574.hybirdfilexfer.Main.main(Main.java:30)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(Unknown Source)
        at sun.nio.ch.FileChannelImpl.transferFrom(Unknown Source)
        at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.transferData(ReceiveFilesCall.java:108)
        at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.receiveFileSlice(ReceiveFilesCall.java:98)
        at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.call(ReceiveFilesCall.java:22)
        at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.call(ReceiveFilesCall.java:7)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
接收文件时发生异常，客户端已退出

**Comment by TJNOV** [comment]
> USB_ADB_receive 已中断，如果本程序（电脑端）没有正常结束，请手动关闭！ java.util.concurrent.ExecutionException: java.io.IOException: 远程主机强迫关闭了一个现有的连接。 at java.util.concurrent.FutureTask.report(Unknown Source) at java.util.concurrent.FutureTask.get(Unknown Source) at top.weixiansen574.hybirdfilexfer.core.HFXClient.handleReceiveFiles(HFXClient.java:240) at top.weixiansen574.hybirdfilexfer.core.HFXClient.start(HFXClient.java:111) at top.weixiansen574.hybirdfilexfer.Main.main(Main.java:30) Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。 at sun.nio.ch.SocketDispatcher.read0(Native Method) at sun.nio.ch.SocketDispatcher.read(Unknown Source) at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) at sun.nio.ch.IOUtil.read(Unknown Source) at sun.nio.ch.SocketChannelImpl.read(Unknown Source) at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(Unknown Source) at sun.nio.ch.FileChannelImpl.transferFrom(Unknown Source) at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.transferData(ReceiveFilesCall.java:108) at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.receiveFileSlice(ReceiveFilesCall.java:98) at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.call(ReceiveFilesCall.java:22) at top.weixiansen574.hybirdfilexfer.core.ReceiveFilesCall.call(ReceiveFilesCall.java:7) at java.util.concurrent.FutureTask.run(Unknown Source) at java.lang.Thread.run(Unknown Source) 接收文件时发生异常，客户端已退出

只要一锁屏、或者息屏就会终端
