### ISSUE TITLE
[BugReport]Java报错

### ISSUE THREAD

**Issue by AlphatoBeta** [weixiansen574/HybridFileXfer#56]
运行环境windows11 x64 
1.测试本机java可用性
C:\Users\***> java -version
java version "17.0.12" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)
2.运行“启动_ADB连接.bat”报错
C:\Software\HybridFileXfer>java -jar HybridFileXfer.jar -c adb
USB_ADB : 5740 端口转发成功！
正在连接 网卡名：USB_ADB 远程地址：127.0.0.1 绑定地址：null
正在连接 网卡名：wlan0 远程地址：192.168.110.156 绑定地址：null
Exception in thread "main" java.net.SocketException: Permission denied: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:586)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853)
        at java.base/java.nio.channels.SocketChannel.open(SocketChannel.java:285)
        at top.weixiansen574.hybirdfilexfer.core.HFXClient.connect(HFXClient.java:85)
        at top.weixiansen574.hybirdfilexfer.Main.main(Main.java:29)

**Comment by AlphatoBeta** [comment]
解决了 是防火墙问题

**Comment by AlphatoBeta** [comment]
解决了，是防火墙问题
