### ISSUE TITLE
【bug】传输文件时被强制中断

### ISSUE THREAD

**Issue by LINKlang** [weixiansen574/HybridFileXfer#8]
如题，我在传输一个7.59GB的zip文件时，遇到了异常错误，手机app立即报错提示[忘截屏了]，同时windows控制台也出现报错
```
java.io.EOFException
        at java.base/java.io.DataInputStream.readShort(DataInputStream.java:321)
        at top.weixiansen574.hybridfilexfer.core.threads.ClientControllerThread.waitingForRequest(ClientControllerThread.java:106)
        at top.weixiansen574.hybridfilexfer.core.threads.ClientControllerThread.run(ClientControllerThread.java:86)
```
![image](https://github.com/weixiansen574/HybridFileXfer/assets/116951234/57bfc09d-69b6-47b9-93a9-79b9ff602a51)

**Comment by weixiansen574** [comment]
wifiReceive线程没动吗？

**Comment by LINKlang** [comment]
> wifiReceive线程没动吗？

手机端有显示，pc端没log

**Comment by weixiansen574** [comment]
录个屏

**Comment by LINKlang** [comment]
> 录个屏

现在不会了，这个似乎是概率性bug

**Comment by LINKlang** [comment]
@weixiansen574 这个问题好像是程序bug，我刚刚传输了一段13mb的视频，就算是传输完了，终端控制台还是提示eof了
```usbReceive 接收线程已终止，因为发生了异常
java.io.EOFException
wifiReceive 接收线程已终止，因为发生了异常
        at java.base/java.io.DataInputStream.readShort(DataInputStream.java:321)
        at top.weixiansen574.hybridfilexfer.core.threads.ReceiveThread.run(ReceiveThread.java:29)
java.io.EOFException
```
![image](https://github.com/weixiansen574/HybridFileXfer/assets/116951234/6fac4599-7e16-49b8-ae64-a11d910dea97)

**Comment by weixiansen574** [comment]
你WIFI不稳定吗？若果可以，尽量找到复现方法，并且录屏

**Comment by jacobin** [comment]
> @weixiansen574 这个问题好像是程序bug，我刚刚传输了一段13mb的视频，就算是传输完了，终端控制台还是提示eof了
> 
> ```
> java.io.EOFException
> wifiReceive 接收线程已终止，因为发生了异常
>         at java.base/java.io.DataInputStream.readShort(DataInputStream.java:321)
>         at top.weixiansen574.hybridfilexfer.core.threads.ReceiveThread.run(ReceiveThread.java:29)
> java.io.EOFException
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/116951234/326014364-6fac4599-7e16-49b8-ae64-a11d910dea97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzA5MjksIm5iZiI6MTcyMTY3MDYyOSwicGF0aCI6Ii8xMTY5NTEyMzQvMzI2MDE0MzY0LTZmYWM0NTk5LTdlMTYtNDliOC1hZTY0LWExMWQ5MTBkZWE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNzUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTg0ZTEyYzFiZDdhMGU1NjczNjhmZTFhYWNkNzU5YTc4OGUxOTQ3ZWVlMTQ3MjIwMGRiYjMzMTFiNjcwYmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dBmB99W76XqBMQcAtKa69Ejg-kJB2rCQsogqRtCHqSk)




> @weixiansen574 这个问题好像是程序bug，我刚刚传输了一段13mb的视频，就算是传输完了，终端控制台还是提示eof了
> 
> ```
> java.io.EOFException
> wifiReceive 接收线程已终止，因为发生了异常
>         at java.base/java.io.DataInputStream.readShort(DataInputStream.java:321)
>         at top.weixiansen574.hybridfilexfer.core.threads.ReceiveThread.run(ReceiveThread.java:29)
> java.io.EOFException
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/116951234/326014364-6fac4599-7e16-49b8-ae64-a11d910dea97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzA5MjksIm5iZiI6MTcyMTY3MDYyOSwicGF0aCI6Ii8xMTY5NTEyMzQvMzI2MDE0MzY0LTZmYWM0NTk5LTdlMTYtNDliOC1hZTY0LWExMWQ5MTBkZWE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNzUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTg0ZTEyYzFiZDdhMGU1NjczNjhmZTFhYWNkNzU5YTc4OGUxOTQ3ZWVlMTQ3MjIwMGRiYjMzMTFiNjcwYmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dBmB99W76XqBMQcAtKa69Ejg-kJB2rCQsogqRtCHqSk)

https://github.com/weixiansen574/HybridFileXfer/issues/34
